version: '2'

services:

  zookeeper_web:
    image: elkozmon/zoonavigator-web:latest
    container_name: zoonavigator-web
    ports:
     - "8000:8000"
    extra_hosts:
      zookeeper1: 172.20.20.21
      zookeeper2: 172.20.20.22
      zookeeper3: 172.20.20.23
    environment:
      API_HOST: "zookeeper_api"
      API_PORT: 9000
    depends_on:
     - zookeeper_api
    restart: always

  zookeeper_api:
    image: elkozmon/zoonavigator-api:latest
    container_name: zoonavigator-api
    extra_hosts:
      zookeeper1: 172.20.20.21
      zookeeper2: 172.20.20.22
      zookeeper3: 172.20.20.23
    environment:
      SERVER_HTTP_PORT: 9000
    restart: always

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    extra_hosts:
      zookeeper1: 172.20.20.21
      zookeeper2: 172.20.20.22
      zookeeper3: 172.20.20.23
      kafka1: 172.20.20.21
      kafka2: 172.20.20.22
      kafka3: 172.20.20.23
    ports:
      - "8084:9000"
    environment:
      ZK_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    restart: always

  schema_registry:
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: schema_registry
    container_name: schema_registry
    extra_hosts:
      zookeeper1: 172.20.20.21
      zookeeper2: 172.20.20.22
      zookeeper3: 172.20.20.23
      kafka1: 172.20.20.21
      kafka2: 172.20.20.22
      kafka3: 172.20.20.23
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,OPTIONS'
    restart: always

  rest-proxy:
    image: confluentinc/cp-kafka-rest
    hostname: rest-proxy
    depends_on:
      - schema_registry
    extra_hosts:
      zookeeper1: 172.20.20.21
      zookeeper2: 172.20.20.22
      zookeeper3: 172.20.20.23
      kafka1: 172.20.20.21
      kafka2: 172.20.20.22
      kafka3: 172.20.20.23
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      KAFKA_REST_HOST_NAME: 'rest-proxy'
    restart: always

  kafka-topic-ui:
    image: landoop/kafka-topics-ui:0.9.2
    ports:
      - "8083:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
    depends_on:
      - rest-proxy
    restart: always
 
  kafka_drop:
    image: obsidiandynamics/kafdrop
    ports:
      - "8086:9000"
    extra_hosts:
      zookeeper1: 172.20.20.21
      zookeeper2: 172.20.20.22
      zookeeper3: 172.20.20.23
      kafka1: 172.20.20.21
      kafka2: 172.20.20.22
      kafka3: 172.20.20.23
    environment:
      KAFKA_BROKERCONNECT: kafka1:9092,kafka2:9092,kafka3:9092
    restart: always